3 add custom terms date in form
CapSens/loan-creator-web pull request #3
Opened 2021-04-26 12:42 UTC by AJuliette

https://trello.com/c/hAVDgK19/9-13-loan-creator-web-possibilit%C3%A9-de-modifier-les-dates-directement-dans-l%C3%A9ch%C3%A9ancier-au-r%C3%A9el

2021-05-04 12:45 UTC, Mziserman approved these changes

2021-05-05 08:27 UTC, AntoineBecquet requested changes
Le commentaire sur `to_right_format` n'est pas important mais je pense que celui sur le js l'est

2021-05-05 08:27 UTC, AntoineBecquet commented on lib/loan_creator_web/views/table.erb
> +  <input type="button" onclick="updateWithDates()" class="btn btn-primary btn-lg my-2" value="update">
Tu peux faire un bouton contenant directement le paramètre voulu, le javascript n'est pas nécessaire.

```
<%= button_tag "Update", class: "btn btn-primary btn-lg my-2", name: :foo, value: :bar %>
```

2021-05-05 08:27 UTC, AntoineBecquet commented on lib/loan_creator_web/helpers/application_helper.rb
> +        value.map{|k, v| v}
`value.values` ?

Est-ce que les paramètres ne peuvent pas être passés sous la forme d'un tableau plutôt qu'un hash si les clés n'ont pas d'importance ?

2021-05-05 08:27 UTC, AntoineBecquet commented on lib/loan_creator_web/views/script.erb
> +    document.forms[0].submit();
Il faudrait référencer le form plus précisément, par exemple avec son id, parce que là si on ajoute un deuxième form au dessus du premier cette fonction ne se comporte plus comme prévu.

Mais comme dit dans l'autre commentaire, on peut gérer proprement ce paramètre dans le bouton et ce js n'est pas nécessaire.

2021-05-05 14:57 UTC, AJuliette commented on lib/loan_creator_web/views/table.erb
> +  <input type="button" onclick="updateWithDates()" class="btn btn-primary btn-lg my-2" value="update">
:o

2021-05-05 15:05 UTC, AJuliette commented on lib/loan_creator_web/views/table.erb
> +  <input type="button" onclick="updateWithDates()" class="btn btn-primary btn-lg my-2" value="update">
Ah mais c'est du Rails et on est sous Sinatra là @AntoineBecquet

2021-05-05 16:58 UTC, AntoineBecquet requested changes

2021-05-05 16:58 UTC, AntoineBecquet commented on lib/loan_creator_web/helpers/application_helper.rb
> +        value
pourquoi appeler `to_right_format` si rien n'est fait dans ce cas ?

2021-05-05 16:58 UTC, AntoineBecquet commented on lib/loan_creator_web/views/table.erb
> +  <input type="button" onclick="updateWithDates()" class="btn btn-primary btn-lg my-2" value="update">
Le helper `button_tag` vient de rails oui pardon, mais la balise `button` c'est du html standard non ?

https://developer.mozilla.org/fr/docs/Web/HTML/Element/Button

2021-05-11 16:22 UTC, AJuliette commented on lib/loan_creator_web/views/table.erb
> +  <input type="button" onclick="updateWithDates()" class="btn btn-primary btn-lg my-2" value="update">
Ah vi

2021-05-12 16:39 UTC, AntoineBecquet approved these changes

2021-05-12 16:39 UTC, merged