22/capitalization boolean
CapSens/loan-creator-web pull request #5
Opened 2021-11-12 16:15 UTC by Melrt

https://trello.com/c/c7jkRCS4/22-inclure-le-booleen-qui-indique-si-on-capitalise-annuellement-les-int%C3%A9r%C3%AAts-d%C3%A9ch%C3%A9ances-sup%C3%A9rieures-%C3%A0-1-an

J'ai mergé ma branche précédente qui était nécessaire pour mes tests.

Et j'ai eu la joie de découvrir les limites des checkbox qui n'envoient un params QUE quand le bouton est checked.. J'ai donc trouvé une sorcellerie étrange dans les fins fonds de Stackoverflow pour fixer le problème, une solution plus propre est la bienvenue.

Et ce n'est pas dans le ticket, mais Jullian m'a demandé d'arrondir les Float

2021-11-15 14:35 UTC, AntoineBecquet requested changes

2021-11-15 14:35 UTC, AntoineBecquet commented on lib/loan_creator_web/views/form.erb
> +</div>
Ce que fait Rails, et que tu peux faire ici aussi, c'est d'avoir une valeur "non cochée" par défaut avant la checkbox.
Tu peux avoir plusieurs inputs avec le même nom dans ton formulaire, dans ce cas c'est le dernier qui s'applique en priorité.
Avoir le même nom pour l'input caché devrait simplifier le reste des conditions.

```
check_box("post", "validated")
# => <input name="post[validated]" type="hidden" value="0" />
#    <input checked="checked" type="checkbox" id="post_validated" name="post[validated]" value="1" />
```
https://apidock.com/rails/ActionView/Helpers/FormHelper/check_box

2021-11-23 08:20 UTC, Melrt commented on lib/loan_creator_web/views/form.erb
> +</div>
J'ai du mal à voir comme l'appliquer dans mon code car je n'ai pas d'objet pour pouvoir créer un formulaire rails

2021-11-23 08:43 UTC, Melrt commented on lib/loan_creator_web/views/form.erb
> +</div>
J'ai du mal à voir quelle différence ca ferait 
Car dans mon HTML j'aurai ca : 
```
<div class="my-2">
  <label class="switch">
  <input name="multi_part_interests_calculation" type="hidden" value="0" />
  <input type="checkbox" name="multi_part_interests_calculation" value="1" <%= checked_default_true %>/>
  <span class="slider round"></span>
  </label>
  <span>Capitalization of maturities > 1 year</span>
</div>
```

Et dans mon helper :
    ```
 def checked_default_true
      if params[:multi_part_interests_calculation] == "1"
        'checked'
      elsif params[:multi_part_interests_calculation] == "0"
        ''
      else
        'checked'
      end
    end
```

Je ne vois pas comment faire autrement 🤔 Et donc la ca revient au même que ce que j'avais fait
Car j'ai besoin que la checkbox soit cochée par défaut

2021-11-23 10:59 UTC, AntoineBecquet commented on lib/loan_creator_web/views/form.erb
> +</div>
Ça fait un paramètre de moins déjà.

Et tu peux encore simplifier `check_default_true`, la première condition est superflue là.

2021-11-23 17:12 UTC, Melrt commented on lib/loan_creator_web/views/form.erb
> +</div>
Ah oui pour le params en effet ! 
Mais pour la condition si je la simplifie, je ne peux pas garder 'checked' comme valeur de depart quand il n'y à encore aucun params

2021-11-26 08:48 UTC, AntoineBecquet approved these changes

2021-11-26 08:48 UTC, merged